
var isfullscreen=false;var embedded_mcfh=0;var embedded_mch=0;var embedded_mcw=0;var embedded_header_height=0;var leftbar_width=0;var feedbackcentered=false;var popupcentered=false;var childpopupcentered=false;var inframe=(window.location!=window.parent.location)?true:false;$(document).on('change','.btn-file :file',function(){var input=$(this),numFiles=input.get(0).files?input.get(0).files.length:1,label=input.val().replace(/\\/g,'/').replace(/.*\//,'');input.trigger('fileselect',[numFiles,label]);});$(document).ready(function(){$('body').tooltip({selector:'.tt-bind',container:'body'});$('.tt-delay-bind').tooltip({container:'body',delay:{show:1200,hide:100}});$('.pop').popover({html:true});$('.sk-spinner-center').center(false);$('body').tooltip({selector:'[rel=tooltip]'});$('body').on('click','.msg-show-details',function(){if($('.msg-details').is(':visible')){$('.msg-show-details').html(_('Show Details')+' <i class="fa fa-chevron-up"></i>');$('.msg-details').hide();}else{$('.msg-show-details').html(_('Hide Details')+' <i class="fa fa-chevron-down"></i>');$('.msg-details').show();}});$('.btn-file :file').on('fileselect',function(event,numFiles,label){var input=$(this).parents('.input-group').find(':text');$(input).val(label);});if(!inframe){if($('body > .enterprisefeaturenotice').length>0){$('body.child').css('padding-top','31px');}}
if(window==top){resize_content(false);center_content_throbbers();}
$(window).resize(function(){if(window==top){resize_content(false);}
center_content_throbbers();if($('.xi-modal:visible').length>0){$('.xi-modal:visible').center();}
if($('#child_popup_layer').is(":visible")){center_child_popup();}
if($('#popup_layer').is(":visible")){center_popup();}
if($('#whiteout').is(":visible")){clear_whiteout();whiteout();}});$('.servicestatustable').on('change','.tablepagerselect',function(){$('.tablepagerselect').val($(this).val());});$('.servicestatustable').on('keyup','.tablepagertextfield',function(){$('.tablepagertextfield').val($(this).val());});$('.hoststatustable').on('change','.tablepagerselect',function(){$('.tablepagerselect').val($(this).val());});$('.hoststatustable').on('keyup','.tablepagertextfield',function(){$('.tablepagertextfield').val($(this).val());});$("#closetrialnotice").click(function(){var p=this.parentNode;var gp=p.parentNode;$(gp).remove();var optsarr={"ignore_trial_notice":1};var opts=array2json(optsarr);get_ajax_data("setsessionvars",opts);$('#maincontent').css('top','inherit');});$("#closefreenotice").click(function(){var p=this.parentNode;var gp=p.parentNode;$(gp).remove();var optsarr={"ignore_free_notice":1};var opts=array2json(optsarr);get_ajax_data("setsessionvars",opts);$('#maincontent').css('top','inherit');});$("#topmenucontainer ul.menu li a").click(function(){show_throbber();});$('#maincontentframe').load(function(){try{if($('#maincontentframe').contents().find('.enterprisefeaturenotice').length>0){var v=$('#maincontentframe').contents().find('.enterprisefeaturenotice').outerHeight();var tpad=v+$('.parenthead').outerHeight();if($('.contentheadernotice').length>0){tpad+=$('.contentheadernotice').outerHeight();}
$('#fullscreen').css('top',tpad+'px');$('#maincontentframe').contents().find('.childpage').css('margin-top',v+'px');}else{$('#fullscreen').removeAttr('style');}}catch(e){}});$("#fullscreen").click(function(){var x=1;if(!isfullscreen){$("body").css("margin","0");$("#leftnav").hide();$("#header").hide();$("#footer").hide();$("#viewtools").hide();isfullscreen=true;$("#maincontentframe").css('width',"100%");$('#fullscreen').css('left','0px');$('#fullscreen').css('top','0px');$('#fullscreen').removeClass('fs-open').addClass('fs-close');do_fullscreen();}else{$("body").css("margin",bodymargin+"px");$("#leftnav").show();$("#header").show();$("#footer").show();$("#viewtools").show();isfullscreen=false;if($('#leftnav').is(':visible')){$('#fullscreen').css('left','200px');}else{$('#fullscreen').css('left','0px');}
$('#fullscreen').removeClass('fs-close').addClass('fs-open');try{if($('#maincontentframe').contents().find('.enterprisefeaturenotice').length>0){var tpad=$('#maincontentframe').contents().find('.enterprisefeaturenotice').outerHeight()+$('.parenthead').outerHeight();$('#fullscreen').css('top',tpad+'px');}else{$('#fullscreen').removeAttr('style');}}catch(e){}
resize_content();}});$.widget("custom.myautocomplete",$.ui.autocomplete,{_renderMenu:function(ul,items){var that=this,currentCategory="";ul.addClass('dropdown-menu');$.each(items,function(index,item){if(typeof item.category!=="undefined"&&item.category!=currentCategory){ul.append('<li class="dropdown-header">'+item.category+'</li>');currentCategory=item.category;}
that._renderItemData(ul,item);});}});$("#hostsearchBox").each(function(){$(this).myautocomplete({source:suggest_url+'?type=host',minLength:1});});$("#userList #searchBox").each(function(){$(this).myautocomplete({source:suggest_url+'?type=users',minLength:1});});$("#perfgraphspage #searchBox").each(function(){$(this).myautocomplete({source:suggest_url+'?type=host',minLength:1});});$("#navbarSearchBox").each(function(){$(this).myautocomplete({source:suggest_url+'?type=multi',minLength:1,select:function(e,ui){$('#maincontentframe').attr('src',ui.item.url);e.preventDefault();$("#navbarSearchBox").val('');}});});$("#searchBox").focus(function(){if($(this).is(".newdata")){}else{this.value="";$(this).addClass("newdata");}});$("#hostsearchBox").focus(function(){if($(this).is(".newdata")){}else{this.value="";$(this).addClass("newdata");}});$('.btn-report-action').on('mouseup',function(e){var href=$(this).data('url');var url=location.pathname+"?"+$("form").serialize();href+="&url="+encodeURIComponent(url);if(e.which==2){window.open(href);}else if(e.which==1){window.location=href;}});var datepickerup=false;$.datepicker.setDefaults({closeText:'X',altFormat:'yy-mm-dd',dateFormat:'yy-mm-dd'});$('.reportstartdatepicker').click(function(){if(datepickerup){$('#startdatepickercontainer').datepicker('destroy');datepickerup=false;}else{datepickerup=true;$('#startdatepickercontainer').datepicker({closeText:'X',onSelect:function(dateText,inst){$('#startdateBox').val(dateText);$('#startdatepickercontainer').datepicker('destroy');$('#reportperiodDropdown').val('custom');}});}});$('.reportenddatepicker').click(function(){if(datepickerup){$('#enddatepickercontainer').datepicker('destroy');datepickerup=false;}else{datepickerup=true;$('#enddatepickercontainer').datepicker({closeText:'X',onSelect:function(dateText,inst){$('#enddateBox').val(dateText.concat(' 23:59:59'));$('#enddatepickercontainer').datepicker('destroy');$('#reportperiodDropdown').val('custom');}});}});if($('#tab_hash').val()){$("#tabs").tabs({activate:function(event,ui){var href=$(ui.newTab).find('a').prop('href');var hash=href.substring(href.indexOf('#')+1);if(history.pushState){history.pushState(null,null,'#'+hash);}else{window.location.hash=hash;}
$('#'+$('#tab_hash').val()).val(hash);}}).show();}
$("#schedulepagereport a").click(function(){regexpNagiosChild=/(http[s]?:\/\/)(.*\/nagiosxi\/)(.*)/;var success=true;var baseurl=base_url+"/includes/components/scheduledreporting/schedulereport.php?type=page";try{var windowurl=$('#maincontentframe').contents()[0].URL;}catch(err){success=false;}
var xi_basedir=1;var newwindowurl='';if(success){if(windowurl.match(regexpNagiosChild)){newwindowurl=RegExp.$3;}else{newwindowurl=windowurl;xi_basedir=0;}
var theurl=baseurl+"&url="+encodeURIComponent(newwindowurl)+"&wurl="+encodeURIComponent(windowurl)+"&xi_basedir="+xi_basedir;$("#maincontentframe").attr({src:theurl});}else{alert(_("Cannot schedule outside pages.")+"\n\n"+_("Any page not under nagiosxi cannot be scheduled."));}});$("#permalink a").click(function(){show_throbber();var baseurl=permalink_base;var parser=document.createElement('a');parser.href=$('#maincontentframe').contents()[0].URL;var url=parser.pathname+parser.search+parser.hash;var theurl=decodeURIComponent(permalink_base)+"xiwindow="+url;var jsurl=base_url+"/includes/js/jquery/";content="<form><div id='popup_header'><b>"+_('Permalink')+"</b></div><div id='popup_data'><p>"+_('Copy the URL below to retain a direct link to your current view.')+"</p></div><div style='margin-bottom: 10px;'><input type='text' size='50' class='textfield form-control' style='width: 100%;' name='url' id='permalinkURLBox' value='"+theurl+"'></div><div><a id='permalink-copy' href='#' data-clipboard-target='#permalinkURLBox' class='btn btn-sm btn-copy btn-primary'>"+_('Copy to Clipboard')+"</a></div></form><script>$('.btn-copy').tooltip({ trigger: 'click', placement: 'bottom' }); var clipboard = new Clipboard('.btn-copy'); clipboard.on('success', function(e) { setTooltip(e.trigger, '"+_('Copied')+"!'); hideTooltip(e.trigger); }); clipboard.on('error', function(e) { setTooltip(e.trigger, '"+_('Press Ctrl+C to copy')+"'); hideTooltip(e.trigger); });</script>";$("#popup_layer").draggable({disabled:true});hide_throbber();set_popup_content(content);display_popup(450);});$("#keepalive").each(function(){$(this).everyTime(5*60*1000,"keepalivetimer",function(i){get_ajax_data("keepalive",i);});});$(".menusectiontitle").click(function(e){var target=$(e.target);if(target.is('a')){return;}
var menusection=$(this).parents('.menusection');if(menusection.hasClass("menusection-collapsed")){menusection.removeClass("menusection-collapsed");menusection.find('.fa.fa-chevron-up').removeClass('fa-chevron-up').addClass('fa-chevron-down').attr('title','');var optsarr={"keyname":"menu_collapse_options","menuid":$(this).data('id'),"keyvalue":1,"autoload":false};var opts=array2json(optsarr);get_ajax_data('setusermeta',opts);}else{menusection.addClass("menusection-collapsed");menusection.find('.fa.fa-chevron-down').removeClass('fa-chevron-down').addClass('fa-chevron-up').attr('title','');var optsarr={"keyname":"menu_collapse_options","menuid":$(this).data('id'),"keyvalue":0,"autoload":false};var opts=array2json(optsarr);get_ajax_data('setusermeta',opts);}});$("#popout a").click(function(){var theurl=$('#maincontentframe').contents()[0].URL;window.open(theurl);});$("#popup_layer").each(function(){$(this).draggable();});$("#close_popup_link").click(function(){close_popup();});$("#child_popup_layer").each(function(){$(this).draggable();});$("#close_child_popup_link").click(function(){close_child_popup();clear_whiteout();});$("#child_popup_layer").on('click',".close_child_popup_btn",function(){close_child_popup();clear_whiteout();});$(":submit").click(function(){hide_message();});$("#get_online_help_link").click(function(){hide_throbber();});$(".tablesorter tbody tr td a").click(function(){hide_throbber();});$("#feedbacklayer a").click(function(){hide_throbber();});$("#notices a").click(function(){hide_throbber();});$('#tabs ul.tabnavigation a i').parent().find("span").hide();$('#tabs ul.tabnavigation li').first().find("span").show();$('#tabs ul.tabnavigation a i').parent().tooltip();$('#tabs ul.tabnavigation a').click(function(){$('#tabs ul.tabnavigation a i').parent().find("span").hide();$(this).find("span").show();});$("#notices").draggable();$("#close_notices_link").click(function(){hide_throbber();$.ajax({type:"POST",url:this.href,nsp:nsp_str});$("#notices").remove();return false;});$("#feedback_layer").each(function(){$(this).draggable();});$("#close_feedback_link").click(function(){hide_throbber();$("#feedback_layer").css("visibility","hidden");});$("#feedback a").click(function(){show_throbber();if(!feedbackcentered){center_feedback();}
hide_throbber();$("#feedback_layer").css("visibility","visible");$("#feedback_container").each(function(){if(this.origHTML){this.innerHTML=this.origHTML;}});$("#feedback_form textarea").each(function(){this.value='';});init_feedback_submit();});$('#open-search').click(function(){$(this).hide();$('.search-field').fadeIn('fast');$('input.search-query').focus();});$('input.search-query').blur(function(){var s=$(this).val();if(s==""){$('.search-field').hide();$('#open-search').show();}});function init_feedback_submit()
{$("#feedback_form").submit(function(){hide_throbber();var params={};$(this).find(":input, :password, :checkbox, :radio, :submit, :reset").each(function(){params[this.name||this.id||this.parentNode.name||this.parentNode.id]=this.value;});$.ajax({type:"POST",url:this.getAttribute("action"),data:params,beforeSend:function(XMLHttpRequest){$("#feedback_container").each(function(){this.origHTML=this.innerHTML;this.innerHTML="<div id='feedback_header'><b>"+_('Sending Feedback')+"...</b></div><div id='feedback_data'><p>"+_('Please Wait')+"...</p><div id='feedback_throbber'></div></div>";});},success:function(msg){$("#feedback_container").each(function(){this.innerHTML="<div id='feedback_header'><b>"+_("Thank You!")+"</b></div><div id='feedback_data'><p>"+_("Thanks for helping to make this product better! We will review your comments as soon as we get a chance. Until then, kudos to you for being awesome and helping drive innovation!<br><br> - The Dedicated Team @ Nagios Enterprises")+"</p></div>";});},error:function(msg){$("#feedback_container").each(function(){this.innerHTML="<div id='feedback_header'><b>"+_('Error')+"</b></div><div id='feedback_data'><p>"+_('An error occurred. Please try again later.')+"</p></div>";});}});return false;});}
$(document).keydown(function(e){if(e.keyCode==116||(e.ctrlKey&&e.keyCode==82)){if(inframe){e.preventDefault();e.stopPropagation();self.location.reload(true);}else{if($('#maincontentframe').length>0){e.preventDefault();e.stopPropagation();document.getElementById('maincontentframe').contentDocument.location.reload(true);}}}});});function exporting_url(exporting_object,export_type){var export_rrd_url="/nagiosxi/includes/components/xicore/export-rrd.php";window.location=export_rrd_url+'?host='+exporting_object.host+'&service='+exporting_object.service+'&start='+exporting_object.start+'&end='+exporting_object.end+'&step='+exporting_object.step+'&type='+export_type+'&nsp='+nsp_str;}
function whiteout()
{if(inframe||$('#maincontent').length==0){$('#whiteout').width($(window).width());$('#whiteout').height($(window).height());$('#whiteout').css('position','fixed');$('#whiteout').css('top','0');$('#whiteout').css('left','0');}else{var w=$('#maincontent').width();var h=$('#maincontent').height();var t=$('#maincontent').css('top');var l=$('#maincontent').css('left');$('#whiteout').width(w);$('#whiteout').height(h);$('#whiteout').css('top',t);$('#whiteout').css('left',l);$('#whiteout').css('position','absolute');}
$('#whiteout').show();}
function clear_whiteout()
{if($('.perfdata-popup').is(':visible')){$('#whiteout').css('z-index',9000);return;}
$('#whiteout').hide();}
function blackout()
{blackout_resize();$('#blackout').show();}
function blackout_resize()
{$('#blackout').css('width',$(window).width()+'px');$('#blackout').css('height',$(window).height()+'px');$('#blackout').css('position','fixed');$('#blackout').css('top','0');$('#blackout').css('left','0');}
function clear_blackout()
{$('#blackout').hide();}
function center_feedback()
{var l=$("#feedback_layer");var wh=$(window).height();var ww=$(window).width();var lh=$(l).height();var lw=$(l).width();var newtop=(wh-lh)/2;var newleft=(ww-lw)/2;$("#feedback_layer").css("top",newtop);$("#feedback_layer").css("left",newleft);feedbackcentered=true;}
function center_login_alert_popup()
{var l=$("#feedback_layer");var wh=$(window).height();var ww=$(window).width();var lh=$(l).height();var lw=$(l).width();var newtop=(wh-lh)/2;var newleft=(ww-lw)/2;$("#login_alert_popup").css("top",newtop);$("#login_alert_popup").css("left",newleft);feedbackcentered=true;}
function get_datetime_string(s,z)
{var r="??";$.ajax({type:"GET",async:false,url:ajax_helper_url,data:{cmd:"getdatetimestring",t:s,zs:z,nsp:nsp_str},success:function(data){r=data;}});return r;}
function get_ajax_data(c,o)
{var r="??";$.ajax({type:"GET",async:false,url:ajax_helper_url,data:{cmd:c,opts:o,nsp:nsp_str},success:function(data){r=data;}});return r;}
function get_ajax_data_with_callback(c,o,pfc)
{var r="??";$.ajax({type:"GET",async:true,url:ajax_helper_url,data:{cmd:c,opts:o,nsp:nsp_str},success:function(data){eval(pfc+'("'+escape(data)+'")');}});}
function get_ajax_data_innerHTML(c,o,doasync,obj)
{$.ajax({type:"GET",async:doasync,url:ajax_helper_url,data:{cmd:c,opts:o,nsp:nsp_str},success:function(data){$(obj).html(data);}});return true;}
function bind_tt(data)
{$('.a-tt-bind').tooltip();}
function get_ajax_data_innerHTML_with_callback(c,o,doasync,obj,pfc)
{$.ajax({type:"GET",async:doasync,url:ajax_helper_url,data:{cmd:c,opts:o,nsp:nsp_str},success:function(data){$(obj).html(data);var funcname=pfc+'()';var funcname=pfc+'("'+escape(data)+'")';var x=1;eval(pfc+'("'+escape(data)+'")');}});return true;}
function get_ajax_data_imagesrc(c,o,doasync,obj)
{var r="??";$.ajax({type:"GET",async:doasync,url:ajax_helper_url,data:{cmd:c,opts:o,nsp:nsp_str},success:function(data){obj.src=data;}});return true;}
function get_ajax_data_imagesrc_with_callback(c,o,doasync,obj,pfc)
{var r="??";$.ajax({type:"GET",async:doasync,url:ajax_helper_url,data:{cmd:c,opts:o,nsp:nsp_str},success:function(data){var theobj=obj;obj.src=data;var funcname=pfc+'()';eval(pfc+'()');}});return true;}
function show_throbber(){$("#throbber").css("display","block");}
function hide_throbber(){$("#throbber").css("display","none");}
function hide_message(){$("#message").css("visibility","hidden");}
function remove_message(){$("#message").remove();}
var MCT=0;var MCL=0;function resize_content()
{var h=$(window).height();var w=$(window).width();var mf=$("#mainframe");if(!mf){return;}
var hpad=0;if($('#header').is(':visible')&&$('#footer').is(':visible')){hpad=$('#header').outerHeight()+$('#footer').outerHeight();}
var height=h-hpad;$("#mainframe").css('height',height+"px");var nh=0;if($('.contentheadernotice').length>0){nh=$('.contentheadernotice').outerHeight();}
var mfh=$("#mainframe").outerHeight();$("#leftnav").css('height',mfh-extraheightnav-nh+"px");$("#maincontent").css('height',mfh-extraheight-nh+"px");var mcfw=w-extrawidth;if($('#header').is(':visible')&&$('#footer').is(':visible')){mcfw-=$('#leftnav').outerWidth();}
var mcfh=mfh;$('#maincontent').css('top',nh+'px');if(!$('#header').is(':visible')&&!$('#footer').is(':visible')){$('#maincontent').css('left','0px');}else{if(nh>0){if(MCT==0){var mct=$('#maincontent').css('top');MCT=parseInt(mct.substring(0,mct.length-2));}
$('#maincontent').css('top',(MCT+nh)+'px');}
if($('#header').is(':visible')){$('#maincontent').css('top',$('#header').outerHeight()+nh+'px');}
if($('#leftnav').is(':visible')){$('#maincontent').css('left',$('#leftnav').outerWidth()+'px');}}
try{if($('#maincontentframe').contents().find('.enterprisefeaturenotice').length>0){var tpad=$('#maincontentframe').contents().find('.enterprisefeaturenotice:not(#tabs .enterprisefeaturenotice)').outerHeight();if($('#header').is(':visible')){tpad+=$('.parenthead').outerHeight();}
if($('.contentheadernotice').length>0){tpad+=$('.contentheadernotice').outerHeight();}
$('#fullscreen').css('top',tpad+'px');}}catch(e){}
$("#maincontentframe").css('width',mcfw+"px");$("#maincontent").css('width',mcfw+"px");$("#myviewoverlay").css('height',mcfh-20);$("#myviewoverlay").css('opacity',0.1);}
function do_fullscreen()
{var d=document;if(!d){return;}
var db=document.body;if(!db){return;}
resize_content();}
function display_popup(cwidth,cheight)
{$("#popup_close").each(function(){$(this).css("visibility","visible");});if(cwidth){$("#popup_content").css("width",cwidth);}
if(cheight){$("#popup_content").css("height",cheight);}
$("#popup_layer").css("background-color","#F1F1F1");$("#popup_layer").css("opacity","1.0");$("#popup_layer").css("display","block");var lh=$("#popup_layer").height();var ch=$("#popup_content").height();var chmt=parseInt($("#popup_content").css("margin-top"));var chmb=parseInt($("#popup_content").css("margin-bottom"));height=ch+chmt+chmb;$("#popup_layer").css("height",height);var lw=$("#popup_layer").width();var cw=$("#popup_content").width();var cwmr=parseInt($("#popup_content").css("margin-right"));var cwml=parseInt($("#popup_content").css("margin-left"));width=cw+cwmr+cwml;$("#popup_layer").css("width",width);if(!popupcentered){center_popup();}
$("#popup_layer").css("visibility","visible");$("#popup_layer").each(function(){$(this).fadeIn("fast");});}
function set_popup_content(content)
{$("#popup_container").each(function(){$(this).html(content);});var c=$("#popup_container");}
function fade_popup(color,time)
{time=typeof(time)!='undefined'?time:1000;$("#popup_close").each(function(){$(this).css("visibility","hidden");});$("#popup_layer").each(function(){var c="#D0FF76";if(color=="red"){c="#FF9999";}
var myColors=[{param:'background-color',cycles:"1",isFade:false,colorList:["#F1F1F1",c]}];$(this).colorBlend(myColors);$(this).oneTime(time,"popuptimer",function(i){$(this).fadeOut();$(this).oneTime(500,"popuptimer2",function(i){close_popup();});});});}
function close_popup()
{hide_throbber();$("#popup_close").each(function(){$(this).css("visibility","hidden");});$("#popup_layer").each(function(){$(this).css("visibility","hidden");});}
function center_popup()
{var l=$("#popup_layer");var wh=$(window).height();var ww=$(window).width();var lh=$(l).height();var lw=$(l).width();var newtop=(wh-lh)/2;var newleft=(ww-lw)/2;$("#popup_layer").css("top",newtop);$("#popup_layer").css("left",newleft);popupcentered=true;}
function resize_popup()
{var lh=$("#popup_layer").height();var ch=$("#popup_content").height();var chmt=parseInt($("#popup_content").css("margin-top"));var chmb=parseInt($("#popup_content").css("margin-bottom"));height=ch+chmt+chmb;$("#popup_layer").css("height",height);var lw=$("#popup_layer").width();var cw=$("#popup_content").width();var cwmr=parseInt($("#popup_content").css("margin-right"));var cwml=parseInt($("#popup_content").css("margin-left"));width=cw+cwmr+cwml;$("#popup_layer").css("width",width);}
function resize_child_popup()
{var lh=$("#child_popup_layer").height();var ch=$("#child_popup_content").height();var chmt=parseInt($("#child_popup_content").css("margin-top"));var chmb=parseInt($("#child_popup_content").css("margin-bottom"));height=ch+chmt+chmb;$("#child_popup_layer").css("height",height);var lw=$("#child_popup_layer").width();var cw=$("#child_popup_content").width();var cwmr=parseInt($("#child_popup_content").css("margin-right"));var cwml=parseInt($("#child_popup_content").css("margin-left"));width=cw+cwmr+cwml;$("#child_popup_layer").css("width",width);}
function display_child_popup(h)
{$("#child_popup_layer").css("background-color","#F1F1F1");$("#child_popup_layer").css("opacity","1.0");$("#child_popup_layer").css("display","block");$("#child_popup_layer").css("visibility","visible");if(!childpopupcentered){$("#child_popup_layer").center();}}
function set_child_popup_content(content)
{$("#child_popup_container").each(function(){$(this).html(content);});}
function fade_child_popup(color,time)
{time=typeof(time)!='undefined'?time:1000;$("#child_popup_layer").each(function(){var c="#D0FF76";if(color=="red"){c="#FF9999";}
var myColors=[{param:'background-color',cycles:"1",isFade:false,colorList:["#F1F1F1",c]}];$(this).colorBlend(myColors);$(this).oneTime(time,"child_popuptimer",function(i){$(this).fadeOut();$(this).oneTime(500,"child_popuptimer2",function(i){close_child_popup();});});});}
function close_child_popup()
{hide_throbber();$("#child_popup_layer").css("visibility","hidden");}
function center_child_popup()
{$("#child_popup_layer").center();childpopupcentered=true;}
function center_content_throbbers()
{$('#throbber').center(false);}
function generate_new_api_key(user_id){var optsarr={"func":"set_random_api_key","args":{"user_id":user_id}};var opts=array2json(optsarr);$('#apikey').val(get_ajax_data("getxicoreajax",opts,true));}
function setTooltip(btn,message){$(btn).tooltip('hide').attr('data-original-title',message).tooltip('show');}
function hideTooltip(btn){setTimeout(function(){$(btn).tooltip('hide');},2000);}
function array2json(arr){var parts=[];var is_list=(Object.prototype.toString.apply(arr)==='[object Array]');for(var key in arr){var value=arr[key];if(typeof value=="object"){if(is_list)parts.push(array2json(value));else parts[key]=parts.push('"'+key+'":'+array2json(value));}else{var str="";if(!is_list)str='"'+key+'":';if(typeof value=="number")str+=value;else if(value===false)str+='false';else if(value===true)str+='true';else str+='"'+value+'"';parts.push(str);}}
var json=parts.join(",");if(is_list)return'['+json+']';return'{'+json+'}';}
jQuery.fn.center=function(parent){if(parent){parent=this.parent();}else{parent=window;}
this.css({"position":"absolute","top":((($(parent).height()-this.outerHeight())/2)+$(parent).scrollTop()+"px"),"left":((($(parent).width()-this.outerWidth())/2)+$(parent).scrollLeft()+"px")});return this;}
jQuery.fn.filterByText=function(textbox,selectSingleMatch,minimumTextValue){return this.each(function(){var select=this;var optionsAndOptGroups=[];if(typeof selectSingleMatch==="undefined"){selectSingleMatch=false;}
if(typeof minimumTextValue==="undefined"){minimumTextValue=0;}
$(select).children('option, optgroup').each(function(){optionsAndOptGroups.push($(this));});$(select).data('optionsAndOptGroups',optionsAndOptGroups);$(textbox).bind('keyup',function(e){if(textbox.val().length>minimumTextValue||e.which===46||e.which===8){var optionsAndOptGroups=$(select).empty().data('optionsAndOptGroups');var search=$.trim($(this).val());var regex=new RegExp(search,'gi');$.each(optionsAndOptGroups,function(){if($(this).is('option')){if($(this).text().match(regex)!==null){$(select).append($(this));}}
else{var optionGroupClone=$(this).clone();$.each(optionGroupClone.children('option'),function(){if($(this).text().match(regex)===null){$(this).remove();}});if(optionGroupClone.children().length){$(select).append(optionGroupClone);}}});}
if($(this).val().length>0){$(this).parent().find('.clear-filter').show();}else{$(this).parent().find('.clear-filter').hide();}});if(selectSingleMatch===true&&$(select).children().length===1){$(select).children().get(0).selected=true;}});};