#!/bin/bash -e

. ./xi-sys.cfg
. ./functions.sh

# Check if user already configured repos
if [ -f installed.repos ]; then
    echo "Repos already configured - exiting."
    exit 0
fi
echo "Configuring Repos..."

# Stop if it is not a supported distro
# Soon to be supported?
# - opensuse11 | opensuse12 | opensuse13 | suse11 | suse12 
# - ubuntu12 | ubuntu14 | ubuntu15 | ubuntu16 | debian7 | debian8
case "$dist" in
    el5 | el6 | el7 | ubuntu12 | ubuntu14 | ubuntu15 | ubuntu16 | debian7 | debian8 )
        :
        ;;
    *)
    echo "$dist is not currently supported. Please use CentOS or RHEL versions 5, 6, or 7 instead." >&2
    exit 1
esac

if [ "$distro" = "SUSE LINUX" ]; then
    ./susemods
    echo "Repos configured OK"
    touch installed.repos
    exit 0
fi

if [ "$distro" == "Ubuntu" ]; then 
    #./ubuntumods
    echo "Repos configured OK"
    touch installed.repos
    exit 0
fi

if [ "$distro" == "Debian" ]; then
    ./debianmods
    echo "Repos configured OK"
    touch installed.repos
    exit 0
fi

# Check that the Red Hat installation is valid
if [ "$distro" = "RedHatEnterpriseServer" ] && [ -x /usr/sbin/rhn_check ] && ! /usr/sbin/rhn_check >/dev/null 2>&1; then
    ## Fails initial check with newer subscription method, nested if to check for subscription and proceed correctly if found -SR
    if [ -x /usr/bin/subscription-manager ] && [[ -z `subscription-manager list | grep Status: | grep -qF Subscribed` ]]; then
        echo "Passed New Subscription Check"
    else
        echo "Your Red Hat Installation is not registered or does not have proper entitlements." >&2
        echo "Please register or enable entitlements at rhn.redhat.com." >&2
        exit 1;
    fi
fi

## Check for the proper "Channels" - added conditional to make sure it's not CentOS 6  -MG 
## As already excludes CentOS 6, separated from previous if to correct nested if checks -SR
## Also checks if offline, and 
if [ ! -f $INSTALL_PATH/offline ]; then
    if [ "$dist" = el6 ] && [ "$distro" != "OracleServer" ] && ! rpm -q centos-release && ! rhn-channel -l | grep -q rhel-.\*-server-optional-6 ; then
        ## Fails initial check with newer subscription method, nested if to check for optional repos proceeds correctly if optional is enabled -SR
        if `yum repolist all | grep optional-rpms | grep -qF enabled`; then
            echo "Passed Optional Repo Check"
        else
            echo "ERROR: Please add the 'Optional' channel to your Red Hat systems subscriptions." >&2
            echo "       You can do so in the Redhat Network web interface or using the rhn-channel command." >&2
            echo "       or, install the yum-utils package and use the following command:" >&2
            echo "       yum-config-manager --enable rhel-6-server-optional-rpms" >&2
            exit 1
        fi
    fi
fi

# If we are running an OracleServer, make sure optional is added
if [ "$distro" == "OracleServer" ] && [ "$dist" == "el7" ]; then

    # Remove this crap in el7 so that we can actually install any mysql
    yum remove -y mysql-community-libs mysql-community-common

    if `yum repolist all | grep optional | grep -qF enabled`; then
        echo "Passed Optional Repo Check"
    else
        echo "ERROR: Please enable the 'Optional' repo for your system in:" >&2
        echo "       /etc/yum.repo.d/public-yum-ol7.repo" >&2
        exit 1
    fi
fi
    
# Make sure everything needed is still present, and we should be working 
# with a current system anyway
if [ "$distro" == "CentOS" ] || [ "$distro" == "RedHatEnterpriseServer" ] || [ "$distro" == "OracleServer" ]; then
    if [ "$1" != noupdate ] || [ "$dist" == "el5" ]; then
        echo "Updating system..."
        yum -y update
    fi
fi

##########################################
# ENABLE 64-bit INSTALLS
##########################################

if [ "$dist $arch" = "el5 x86_64" ]; then
    if [ "$INTERACTIVE" != False ]; then
        cat <<-EOF
            ****************************************************************
            WARNING: This script will remove existing RPMs installed on this
                     system, which may result in existing applications being
                     removed!
            ****************************************************************
EOF
        read -p "Do you want to continue? [y/N]: " res
        echo "RESP: $res"
        if [ "$res" != "y" ]; then
            echo "Exiting"
            exit 0
        fi
    fi

    echo "64-bit system detected, modifying yum"
    cat >>/etc/yum.conf <<-EOF

# Modifications by Nagios XI installer
multilib_policy=best
exclude=*.i?86
EOF

    # 32-bit librsvg2 must be removed before 32-bit gtk2 to avoid armageddon
    if rpm -q librsvg2.i386 >/dev/null; then
        yum -y remove librsvg2.i386
    fi
    yum -y remove \*.i?86
fi

##########################################
# INSTALL DEPENDANT REPOS
##########################################

# See if we need to install RPMForge...
if [ "$distro" == "CentOS" ] || [ "$distro" == "RedHatEnterpriseServer" ] || [ "$distro" == "OracleServer" ]; then
    if ! rpm -q nagios-repo &>/dev/null; then

        echo "Enabling Nagios repo..."
        PKG="packages/nagios-repo-$ver-2.el$ver.noarch.rpm"
        echo "Installing Nagios Repo PKG: $PKG"
        rpm -Uvh "$PKG"
        rm "$PKG"
        unset PKG
        
        if [ ! -f $INSTALL_PATH/offline ]; then
            yum check-update || true
        fi
    fi

    # See if we need to install EPEL...
    if ! rpm -q epel-release &>/dev/null; then

        echo "Enabling EPEL repo..."
        
        if [ $ver -eq 5 ]; then
            EPELVER="5-4"
        elif [ $ver -eq 7 ]; then
            EPELVER="7-2"
        else
            EPELVER="6-8"
        fi
            
        PKG="./packages/epel-release-$EPELVER.noarch.rpm"
        ##Add logging so we can trace this failure in the future -MG
        echo "Installing EPEL PKG: $PKG"
        rpm -Uvh "$PKG"
        rm "$PKG"
        unset PKG
        
        if [ ! -f $INSTALL_PATH/offline ]; then
            yum check-update || true
        fi
        
    fi

    # Check to make sure RPM was installed
    if rpm -q epel-release &>/dev/null; then
        echo "epel-release RPM installed OK"
    else
        echo "ERROR: epel-release RPM was not installed - exiting." >&2
        exit 1
    fi

    # See if we need to install CentOS 6 Continuous Release...
    if [ "$dist" = el6 ] && rpm -q centos-release &>/dev/null && ! rpm -q centos-release-cr &>/dev/null; then

        echo "Enabling CentOS 6 Continuous Release repo..."
        yum -y install centos-release-cr
        yum check-update || true

        # Check to make sure RPM was installed
        if rpm -q centos-release-cr &>/dev/null; then
            echo "centos-release-cr RPM installed OK"
        else
            echo "ERROR: centos-release-cr RPM was not installed - exiting." >&2
            exit 1
        fi
    fi
fi

# Checks if offline, if so, installs all needed packages now to avoid issues
if [ -f $INSTALL_PATH/offline ]; then
    echo "Updating RPMS, this may take a moment." >&2
    rpm -Uvh $INSTALL_PATH/packages/offlineinstall/rpms/upgrade/*.rpm
    echo "Installing RPMS, this may take a moment." >&2
    rpm -ivh $INSTALL_PATH/packages/offlineinstall/rpms/*.rpm
fi

echo "Repo configured OK"
touch installed.repos