#!/bin/bash -e

. ./xi-sys.cfg

# Was previous step completed?
if [ ! -f installed.sudoers ]; then
    echo "sudoers were not initialized - run previous script" >&2
    exit 1
fi

# Was this step already completed?
if [ -f installed.firewall ]; then
    echo "Firewall rules already configured - skipping."
    exit 0
fi

# Skip firewall configuration for Ubuntu for now
if [ "$distro" == "Ubuntu" ] || [ "$distro" == "Debian" ]; then
    echo "Skipping firewall configuration... Not enabled."
    touch installed.firewall
    exit 0
fi

# UPDATE FIREWALL SETTINGS AND RESTART IPTABLES
# added check for offline and modified config to not unload
if [ -f $INSTALL_PATH/offline ]; then
    cp -f nagiosxi/iptables-config /etc/sysconfig
fi

cp -f nagiosxi/iptables /etc/sysconfig

# Disable dynamic firewall for static iptables firewall (from fedora documentation)
if [ $ver -eq 7 ] && [ "$distro" != "Debian" ]; then
    if [ `command -v firewalld` ]; then
        if [ -z "$RPMINSTALL" ]; then
            yum install iptables-services -y
        fi
        systemctl mask firewalld.service
        systemctl enable iptables.service

        # Save and start up iptables
        systemctl stop firewalld.service
        iptables-save
        systemctl restart iptables.service
    fi
elif [ "$dist" = "suse11" ]; then
    echo "SuSE Firewall"
    # rcSuSEfirewall2 restart
else    
    service iptables restart
fi

echo "Firewall rules updated OK"
touch installed.firewall
