#!/bin/bash -e

. ../../xi-sys.cfg

pkgname="nrpe-2.15"

echo "Installing NRPE..."

# Delete the old archive
rm -rf "$pkgname"

# Extract archive
tar -xzf "$pkgname.tar.gz"

# Make and install 
(
	cd "./$pkgname"
	if [ "$distro" == "Ubuntu" ] || [ "$distro" == "Debian" ]; then
		./configure --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu --enable-command-args
	else
		./configure --enable-command-args
	fi

	make  -j $make_j_flag all
	make install-plugin
	make install-daemon
	make install-xinetd
	make install-daemon-config
)

# Restart xinetd
if [ ! `command -v systemctl` ]; then
	service xinetd restart
else
	systemctl restart xinetd
fi

# Do a simple sanity check to make sure some key files exist...
for f in /usr/local/nagios/bin/nrpe /usr/local/nagios/libexec/check_nrpe ; do
	if [ ! -f "$f" ]; then
		echo "ERROR: NRPE install appears to have failed - exiting.  Missing file = $f"
		exit 1
	fi
done

# Things are okay
echo "NRPE installed OK"

