#!/bin/perl -w

#my ${exec_prefix};
#my ${prefix};
#my ${datarootdir};

my ${prefix}="/usr/local/nagios";
my $use_default_prefix = 0;
if(${prefix} eq "/usr/local/nagios"){
    $use_default_prefix = 1;
}

my ${exec_prefix}="${prefix}";

my ${datarootdir}="${prefix}/share";
if($datarootdir eq "${prefix}/share" && $use_default_prefix == 1){
    $datarootdir="${prefix}/share/pnp";
}

my ${datadir}="${datarootdir}";
if($datadir eq "${prefix}/share" && $use_default_prefix == 1){
    $datadir="${prefix}/share/pnp";
}

my $PERL="/bin/perl";
my $PERL_LIB_PATH="no";
if( $PERL_LIB_PATH ne "no" ){
    $PERL_LIB_PATH_CODE = "use lib '".$PERL_LIB_PATH."';";
}else{
    $PERL_LIB_PATH = "";
    $PERL_LIB_PATH_CODE = "";
}
my $SHELL="/bin/sh";
my $STRIP="/bin/strip";
my $INSTALL="/bin/install -c";
if($INSTALL =~ /^\.\//){
    $INSTALL =~ s/^\.\//\.\.\//;
}
my $INSTALL_OPTS="-o nagios -g nagios";
my $DEBUG="0";
my $PERFDATA_DIR="${prefix}/share/perfdata";
my $PERFDATA_LOG="${prefix}/var/perfdata.log";
my $PERFDATA_SPOOL_DIR="${prefix}/var/spool/perfdata/";
my $RRDTOOL="/bin/rrdtool";
my $RRDS="1";
my $PKG_REL_DATE="05-02-2009";
my $PKG_VERSION="0.4.14";
my $PKG_NAME="pnp";
my $init_dir="/etc/rc.d/init.d";
my $npcd_name="npcd";
my $pp_pl_name="process_perfdata.pl";
my $nagios_user="nagios";
my $nagios_grp="nagios";
my $libexecdir="${exec_prefix}/libexec"; # put all --with-vars before directories
my $localstatedir="${prefix}/var";
my $libdir="${exec_prefix}/lib";
my $sysconfdir="${prefix}/etc";
my $host_os="linux-gnu";

if($sysconfdir eq "${prefix}/etc" && $use_default_prefix == 1 ){
    $sysconfdir="${prefix}/etc/pnp";
}
my $sbindir="${exec_prefix}/sbin";
my $bindir="${exec_prefix}/bin";
my $srcdir=".";

my $CC="gcc";
my $CFLAGS="-g -O2";
my $DEFS="-DHAVE_CONFIG_H";
my $LDFLAGS="";
my $LIBS="";
my $MOD_CFLAGS="-fPIC";
my $MOD_LDFLAGS="-shared";

my $CP="/bin/cp";


while ($f = shift @ARGV) {

	if (-x "/bin/mktemp") { 
		$TEMP = `/bin/mktemp $f.$$.XXXXXX`;
		die 'Cannot make temporary file $TEMP' if($?);
		chomp $TEMP;
	} else {
		$XXXXXX = rand;
		$TEMP = "$f.$$.$XXXXXX";
	}

	open(IN,"<$f.in");
	open(OUT,">$TEMP") || die 'Cannot make temporary file $TEMP';

	while (<IN>) {
		s|\@PERL\@|$PERL|g;
		s|\@PERL_LIB_PATH\@|$PERL_LIB_PATH|g;
		s|\@PERL_LIB_PATH_CODE\@|$PERL_LIB_PATH_CODE|g;
		s|\@SHELL\@|$SHELL|g;
		s|\@STRIP\@|$STRIP|g;
		s|\@INSTALL\@|$INSTALL|g;
		s|\@INSTALL_OPTS\@|$INSTALL_OPTS|g;
		s|\@DEBUG\@|$DEBUG|g;
		s|\@PERFDATA_DIR\@|$PERFDATA_DIR|g;
		s|\@PERFDATA_LOG\@|$PERFDATA_LOG|g;
		s|\@PERFDATA_SPOOL_DIR\@|$PERFDATA_SPOOL_DIR|g;
		s|\@RRDTOOL\@|$RRDTOOL|g;
		s|\@RRDS\@|$RRDS|g;
		s|\@PKG_REL_DATE\@|$PKG_REL_DATE|g;
		s|\@PKG_VERSION\@|$PKG_VERSION|g;
		s|\@PKG_NAME\@|$PKG_NAME|g;
		s|\@npcd_name\@|$npcd_name|g;
		s|\@pp_pl_name\@|$pp_pl_name|g;
		s|\@nagios_user\@|$nagios_user|g;
		s|\@nagios_grp\@|$nagios_grp|g;
		s|\@libexecdir\@|$libexecdir|g; # put all --with-vars before directories
		s|\@localstatedir\@|$localstatedir|g;
		s|\@libdir\@|$libdir|g;
		s|\@init_dir\@|$init_dir|g;
		s|\@sysconfdir\@|$sysconfdir|g;
		s|\@datarootdir\@|$datarootdir|g;
		s|\@datadir\@|$datadir|g;
		s|\@sbindir\@|$sbindir|g;
		s|\@bindir\@|$bindir|g;
		s|\@srcdir\@|$srcdir|g;
		s|\@CC\@|$CC|g;
		s|\@CFLAGS\@|$CFLAGS|g;
		s|\@DEFS\@|$DEFS|g;
		s|\@LDFLAGS\@|$LDFLAGS|g;
		s|\@MOD_LDFLAGS\@|$MOD_LDFLAGS|g;
		s|\@MOD_CFLAGS\@|$MOD_CFLAGS|g;
		s|\@LIBS\@|$LIBS|g;
		s|\@CP\@|$CP|g;
		s|\@prefix\@|$prefix|g;
		s|\@host_os\@|$host_os|g;
		s|\$\{exec_prefix\}|$exec_prefix|g; # must be next to last
		s|\$\{prefix\}|$prefix|g; # must be last
		print OUT $_;
	}

	close IN;
	close OUT;

	if ((! -e $f) || (`diff $f $TEMP`)) {
		`mv $TEMP $f`;
	} else {
	         unlink $TEMP;
	}

}
