#!/bin/bash -e

# extract tarball
tar -xzf nagiosmobile.tar.gz

# copy correct apache config
cp -f mods/nagiosmobile_apache.conf nagiosmobile/nagiosmobile_apache.conf
cp -f mods/INSTALL.php nagiosmobile/INSTALL.php

# copy existing include.inc.php is exists
if [ -f /usr/local/nagiosmobile/include.inc.php ];then
    cp -r /usr/local/nagiosmobile/include.inc.php nagiosmobile/
fi

# enter directory and run installer
(
	cd ./nagiosmobile
    chmod +x ./INSTALL.php
	./INSTALL.php
)

# Things are okay
echo "Nagios Mobile installed OK"
